-- Enable Extensions
create extension if not exists vector;
create extension if not exists pg_cron; -- ADDED: Required for entropy cycle

-- 1. HOUSEHOLDS
create table if not exists households (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  created_at timestamptz default now()
);

-- 2. USERS
create table if not exists users (
  id uuid references auth.users not null primary key,
  display_name text,
  metabolic_state_json jsonb default '{"current_goal": "maintenance"}'::jsonb,
  hand_width_mm numeric,
  streak_count integer default 0,
  household_id uuid references households(id),
  created_at timestamptz default now()
);

-- 3. FOODS
create table if not exists foods (
  id bigint generated by default as identity primary key,
  name text not null,
  density_coefficient numeric default 1.0,
  category_decay_rate numeric default 0.05,
  barcode_upc text,
  nutritional_info jsonb
);

-- 4. PANTRY
create table if not exists pantry (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) not null,
  household_id uuid references households(id),
  food_id bigint references foods(id),
  probability_score numeric default 1.0,
  last_verified_at timestamptz default now(),
  status text default 'active'
);

-- 5. FRIENDSHIPS
create table if not exists friendships (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) not null,
  friend_id uuid references users(id) not null,
  status text default 'pending',
  created_at timestamptz default now(),
  unique(user_id, friend_id)
);

-- 6. CONDITIONS
create table if not exists conditions (
  id text primary key,
  name text not null,
  category text,
  strictness text,
  diet_impact text,
  rules_json jsonb not null,
  dga_score numeric default 1.0,
  never_recommend_json jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

-- 7. USER_CONDITIONS
create table if not exists user_conditions (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) not null,
  condition_id text references conditions(id) not null,
  created_at timestamptz default now(),
  unique(user_id, condition_id)
);

-- 8. METABOLIC PHENOMENA
create table if not exists metabolic_phenomena (
  id text primary key,
  name text not null,
  category text,
  mechanism text,
  deepseek_prompt_template text not null,
  created_at timestamptz default now()
);

-- 9. WORKFLOWS
create table if not exists workflows (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references users(id) not null,
  trigger_event text not null,
  last_run_status text default 'pending',
  logs_json jsonb,
  created_at timestamptz default now()
);

-- 10. LOGS
create table if not exists logs (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) not null,
  workflow_id uuid references workflows(id),
  grams numeric,
  metabolic_tags_json jsonb,
  captured_at timestamptz default now()
);

-- 11. CACHE ENTRIES
create table if not exists cache_entries (
  key text primary key,
  value jsonb not null,
  expires_at timestamptz not null
);
create index if not exists idx_cache_expires on cache_entries(expires_at);

-- ADDED: ENTROPY LOGIC (Replaces API Route) =================================

-- Function to run the decay cycle
create or replace function run_entropy_cycle()
returns void
language plpgsql
security definer
as $$
begin
  -- Update probability scores
  -- Formula matches your TS: P_new = P_old * (1 - k)
  -- Uses coalesce(..., 0.05) for default decay rate if null
  update pantry
  set 
    probability_score = greatest(0, probability_score * (1 - coalesce(foods.category_decay_rate, 0.05))),
    status = case 
      when (probability_score * (1 - coalesce(foods.category_decay_rate, 0.05))) < 0.3 then 'review_needed'
      else status
    end
  from foods
  where pantry.food_id = foods.id
  and pantry.status = 'active';
  
end;
$$;

-- Schedule the job (Runs daily at 00:00 GMT)
-- Note: 'cron' schema functions might need explicit schema qualification depending on search_path
select cron.schedule(
  'entropy-daily-cycle',
  '0 0 * * *', 
  'select run_entropy_cycle()'
);

-- END ENTROPY LOGIC ========================================================


-- RLS SECURITY POLICIES
alter table users enable row level security;
alter table foods enable row level security;
alter table pantry enable row level security;
alter table friendships enable row level security;
alter table households enable row level security;
alter table logs enable row level security;
alter table workflows enable row level security;
alter table conditions enable row level security;
alter table user_conditions enable row level security;
alter table metabolic_phenomena enable row level security;
alter table cache_entries enable row level security;

-- USERS POLICIES
drop policy if exists "Users view own profile" on users;
create policy "Users view own profile" on users for select using (auth.uid() = id);

drop policy if exists "Users update own profile" on users;
create policy "Users update own profile" on users for update using (auth.uid() = id);

drop policy if exists "Authenticated view profiles" on users;
create policy "Authenticated view profiles" on users for select using (auth.role() = 'authenticated');

-- FOODS POLICIES
drop policy if exists "Foods read (auth)" on foods;
create policy "Foods read (auth)" on foods for select using (auth.role() = 'authenticated');

drop policy if exists "Foods insert (auth)" on foods;
create policy "Foods insert (auth)" on foods for insert with check (auth.role() = 'authenticated');

-- PANTRY POLICIES
drop policy if exists "Pantry read own" on pantry;
create policy "Pantry read own" on pantry for select using (auth.uid() = user_id);

drop policy if exists "Pantry write own" on pantry;
create policy "Pantry write own" on pantry for insert with check (auth.uid() = user_id);

drop policy if exists "Pantry update own" on pantry;
create policy "Pantry update own" on pantry for update using (auth.uid() = user_id);

-- FRIENDSHIPS POLICIES
drop policy if exists "Friendships read own" on friendships;
create policy "Friendships read own" on friendships for select using (auth.uid() = user_id or auth.uid() = friend_id);

drop policy if exists "Friendships insert requester" on friendships;
create policy "Friendships insert requester" on friendships for insert with check (auth.uid() = user_id);

drop policy if exists "Friendships update receiver" on friendships;
create policy "Friendships update receiver" on friendships for update using (auth.uid() = friend_id);

-- HOUSEHOLDS POLICIES
drop policy if exists "Households read member" on households;
create policy "Households read member" on households for select using (
  exists (select 1 from users u where u.id = auth.uid() and u.household_id = households.id)
);

-- CONDITIONS POLICIES
drop policy if exists "Conditions read (auth)" on conditions;
create policy "Conditions read (auth)" on conditions for select using (auth.role() = 'authenticated');

-- USER_CONDITIONS POLICIES
drop policy if exists "User conditions read own" on user_conditions;
create policy "User conditions read own" on user_conditions for select using (auth.uid() = user_id);

drop policy if exists "User conditions write own" on user_conditions;
create policy "User conditions write own" on user_conditions for insert with check (auth.uid() = user_id);

drop policy if exists "User conditions delete own" on user_conditions;
create policy "User conditions delete own" on user_conditions for delete using (auth.uid() = user_id);

-- METABOLIC PHENOMENA POLICIES
drop policy if exists "Metabolic phenomena read (auth)" on metabolic_phenomena;
create policy "Metabolic phenomena read (auth)" on metabolic_phenomena for select using (auth.role() = 'authenticated');

-- LOGS POLICIES
drop policy if exists "Logs read own" on logs;
create policy "Logs read own" on logs for select using (auth.uid() = user_id);

drop policy if exists "Logs insert own" on logs;
create policy "Logs insert own" on logs for insert with check (auth.uid() = user_id);

-- WORKFLOWS POLICIES
drop policy if exists "Workflows read own" on workflows;
create policy "Workflows read own" on workflows for select using (auth.uid() = user_id);

drop policy if exists "Workflows insert own" on workflows;
create policy "Workflows insert own" on workflows for insert with check (auth.uid() = user_id);

-- CACHE ENTRIES POLICIES
drop policy if exists "Cache read (auth)" on cache_entries;
create policy "Cache read (auth)" on cache_entries for select using (auth.role() = 'authenticated');

drop policy if exists "Cache write (auth)" on cache_entries;
create policy "Cache write (auth)" on cache_entries for insert with check (auth.role() = 'authenticated');

-- Trigger: create public.users row on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, display_name, metabolic_state_json, streak_count)
  values (
    new.id,
    split_part(new.email, '@', 1),
    '{"current_goal":"maintenance"}',
    0
  );
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
