-- Oteka Unified Database Schema (Idempotent)
-- Last Updated: 2026-05-09

/* 
  UNCOMMENT FOR FULL RESET (WARNING: DELETES ALL DATA):
  
  drop trigger if exists on_auth_user_created on auth.users;
  drop function if exists handle_new_user;
  drop table if exists logs cascade;
  drop table if exists workflows cascade;
  drop table if exists pantry cascade;
  drop table if exists foods cascade;
  drop table if exists user_conditions cascade;
  drop table if exists conditions cascade;
  drop table if exists friendships cascade;
  drop table if exists users cascade;
  drop table if exists households cascade;
  drop table if exists cache_entries cascade;
  drop table if exists metabolic_phenomena cascade;
  drop table if exists subscriptions cascade;
  drop table if exists vouchers cascade;
  drop table if exists shopping_list cascade;
*/

-- Enable Extensions
create extension if not exists vector;

create table if not exists households (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  join_code text unique default substring(gen_random_uuid()::text from 1 for 6),
  created_at timestamptz default now()
);

-- 2. USERS
create table if not exists users (
  id uuid references auth.users not null primary key,
  display_name text,
  avatar_url text,
  metabolic_state_json jsonb default '{"current_goal": "maintenance"}'::jsonb,
  hand_width_mm numeric,
  streak_count integer default 0,
  calorie_target integer default 2000,
  household_id uuid references households(id),
  plan text default 'free',
  stripe_customer_id text,
  last_entropy_run date default current_date,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists idx_users_stripe_customer_id on users(stripe_customer_id);
create index if not exists idx_users_household_id on users(household_id);

-- 3. FOODS
create table if not exists foods (
  id bigint generated by default as identity primary key,
  name text not null,
  density_coefficient numeric default 1.0, -- g/cm^3
  category_decay_rate numeric default 0.05, -- daily probability decay
  barcode_upc text unique,
  nutritional_info jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

-- 4. PANTRY
create table if not exists pantry (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) on delete cascade not null,
  household_id uuid references households(id),
  food_id bigint references foods(id),
  name text, -- fallback if food_id is null
  probability_score numeric default 1.0,
  last_verified_at timestamptz default now(),
  status text default 'active', -- active, review_needed, consumed
  metadata_json jsonb default '{}'::jsonb, -- Stores ingredients, micros, packaging info, and remaining_fraction (e.g. 0.25)
  created_at timestamptz default now()
);
create index if not exists idx_pantry_household_id on pantry(household_id);
create index if not exists idx_pantry_user_id on pantry(user_id);
create index if not exists idx_pantry_user_status on pantry(user_id, status);
create index if not exists idx_pantry_food_id on pantry(food_id);

-- 5. FRIENDSHIPS
create table if not exists friendships (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) not null,
  friend_id uuid references users(id) not null,
  status text default 'pending', -- pending, accepted, blocked
  created_at timestamptz default now(),
  unique(user_id, friend_id)
);
create index if not exists idx_friendships_friend_id on friendships(friend_id);

-- 6. CONDITIONS
create table if not exists conditions (
  id text primary key, -- e.g., 'type-1-diabetes', 'keto-strict'
  name text not null,
  category text,
  strictness text,
  diet_impact text,
  rules_json jsonb not null default '{}'::jsonb,
  dga_score numeric default 1.0,
  never_recommend_json jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

-- 7. USER_CONDITIONS
create table if not exists user_conditions (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) not null,
  condition_id text references conditions(id) not null,
  created_at timestamptz default now(),
  unique(user_id, condition_id)
);
create index if not exists idx_user_conditions_condition_id on user_conditions(condition_id);

-- 8. METABOLIC PHENOMENA
create table if not exists metabolic_phenomena (
  id text primary key,
  name text not null,
  category text,
  mechanism text,
  deepseek_prompt_template text not null,
  created_at timestamptz default now()
);

-- 9. WORKFLOWS
create table if not exists workflows (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references users(id) on delete cascade not null,
  trigger_event text not null,
  last_run_status text default 'pending',
  logs_json jsonb default '[]'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 10. LOGS
create table if not exists logs (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) on delete cascade not null,
  workflow_id uuid references workflows(id),
  grams numeric,
  metabolic_tags_json jsonb default '{}'::jsonb,
  local_date text not null default to_char(now() at time zone 'UTC', 'YYYY-MM-DD'),
  captured_at timestamptz default now()
);

-- Performance indices for logs
create index if not exists idx_logs_user_date on logs(user_id, local_date);
create index if not exists idx_logs_user_id on logs(user_id);
create index if not exists idx_logs_user_captured_at on logs(user_id, captured_at desc);
create index if not exists idx_logs_feedback on logs using gin (metabolic_tags_json);
create index if not exists idx_logs_workflow_id on logs(workflow_id);

-- 11. CACHE ENTRIES
create table if not exists cache_entries (
  key text primary key,
  value jsonb not null,
  expires_at timestamptz not null
);
create index if not exists idx_cache_expires on cache_entries(expires_at);

-- ========================================================
-- ENTROPY LOGIC (Daily Probability Decay)
-- ========================================================

-- Function to run the decay cycle for a specific user
-- This is designed for the FREE TIER (called on app load)
create or replace function run_entropy_cycle(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_last_run date;
  v_today date := (to_char(now() at time zone 'UTC', 'YYYY-MM-DD'))::date;
  v_days_diff integer;
begin
  -- Get user's last run date
  select last_entropy_run into v_last_run from users where id = p_user_id;

  -- Default to 1 day if last_run is null (new user)
  if v_last_run is null then
    v_days_diff := 1;
  else
    v_days_diff := v_today - v_last_run;
  end if;

  -- Only run if there is at least a day of difference
  if v_days_diff > 0 then
    -- ATOMIC UPDATE: Run probability decay and status checks in a single block.
    -- pl/pgsql functions execute in a single implicit transaction.
    -- Update items with a linked food_id
    update pantry p
    set 
      probability_score = greatest(0, p.probability_score * power(1 - coalesce(f.category_decay_rate, 0.05) * (2.0 - coalesce((p.metadata_json->>'remaining_fraction')::numeric, 1.0)), v_days_diff)),
      status = case 
        when (p.probability_score * power(1 - coalesce(f.category_decay_rate, 0.05) * (2.0 - coalesce((p.metadata_json->>'remaining_fraction')::numeric, 1.0)), v_days_diff)) < 0.3 then 'review_needed'
        else p.status
      end
    from foods f
    where p.food_id = f.id
      and p.user_id = p_user_id
      and p.status = 'active';

    -- Update custom items (no linked food_id)
    update pantry
    set 
      probability_score = greatest(0, probability_score * power(1 - 0.05 * (2.0 - coalesce((metadata_json->>'remaining_fraction')::numeric, 1.0)), v_days_diff)),
      status = case 
        when (probability_score * power(1 - 0.05 * (2.0 - coalesce((metadata_json->>'remaining_fraction')::numeric, 1.0)), v_days_diff)) < 0.3 then 'review_needed'
        else status
      end
    where user_id = p_user_id
      and status = 'active'
      and food_id is null;

    -- Update last run timestamp for the user
    update users set last_entropy_run = v_today where id = p_user_id;
  end if;

end;
$$;

-- 12. SHOPPING LIST
create table if not exists shopping_list (
  id bigint generated by default as identity primary key,
  household_id uuid references households(id),
  name text not null,
  category text default 'grocery',
  is_checked boolean default false,
  added_by uuid references users(id),
  created_at timestamptz default now()
);
create index if not exists idx_shopping_household_id on shopping_list(household_id);
create index if not exists idx_shopping_list_added_by_household on shopping_list (added_by, household_id);

-- ========================================================
-- RLS SECURITY POLICIES
-- ========================================================

alter table users enable row level security;
alter table foods enable row level security;
alter table pantry enable row level security;
alter table shopping_list enable row level security;
alter table friendships enable row level security;
alter table households enable row level security;
alter table logs enable row level security;
alter table workflows enable row level security;
alter table conditions enable row level security;
alter table user_conditions enable row level security;
alter table metabolic_phenomena enable row level security;
alter table cache_entries enable row level security;

-- HELPER FUNCTIONS FOR RLS
create or replace function get_my_household_id()
returns uuid language sql stable security definer set search_path = public as $$
  select coalesce(
    nullif(current_setting('request.jwt.claims', true)::json->>'household_id', '')::uuid,
    (select household_id from users where id = (select auth.uid()))
  );
$$;

-- USERS
drop policy if exists "Users view own profile" on users;
create policy "Users view own profile" on users for select using (auth.uid() = id);

drop policy if exists "Users update own profile" on users;
create policy "Users update own profile" on users for update using (auth.uid() = id);

drop policy if exists "Authenticated insert profile" on users;
create policy "Authenticated insert profile" on users for insert with check (auth.uid() = id);

drop policy if exists "Authenticated view profiles" on users;
create policy "Authenticated view profiles" on users for select using (auth.role() = 'authenticated');

-- FOODS
drop policy if exists "Foods read (auth)" on foods;
create policy "Foods read (auth)" on foods for select using (auth.role() = 'authenticated');

drop policy if exists "Foods insert (auth)" on foods;
create policy "Foods insert (auth)" on foods for insert with check (auth.role() = 'authenticated');

-- PANTRY (Household Shared)
drop policy if exists "Pantry read household" on pantry;
create policy "Pantry read household" on pantry for select using (
  auth.uid() = user_id or 
  household_id = get_my_household_id()
);

drop policy if exists "Pantry write household" on pantry;
create policy "Pantry write household" on pantry for insert with check (
  auth.uid() = user_id or 
  household_id = get_my_household_id()
);

drop policy if exists "Pantry update household" on pantry;
create policy "Pantry update household" on pantry for update using (
  auth.uid() = user_id or 
  household_id = get_my_household_id()
);

drop policy if exists "Pantry delete household" on pantry;
create policy "Pantry delete household" on pantry for delete using (
  auth.uid() = user_id or 
  household_id = get_my_household_id()
);

-- SHOPPING LIST (Household Shared)
drop policy if exists "Shopping read household" on shopping_list;
create policy "Shopping read household" on shopping_list for select using (
  household_id = get_my_household_id()
);

drop policy if exists "Shopping write household" on shopping_list;
create policy "Shopping write household" on shopping_list for all using (
  household_id = get_my_household_id()
);

-- LOGS / WORKFLOWS
drop policy if exists "Logs access own" on logs;
create policy "Logs manage own" on logs for all using (auth.uid() = user_id);

drop policy if exists "Logs read shared" on logs;
create policy "Logs read shared" on logs for select using (
  auth.uid() = user_id or 
  (select household_id from users where id = logs.user_id) = get_my_household_id() or
  exists (
    select 1 from friendships 
    where friendships.status = 'accepted' 
      and (
        (friendships.user_id = auth.uid() and friendships.friend_id = logs.user_id) or 
        (friendships.user_id = logs.user_id and friendships.friend_id = auth.uid())
      )
  )
);

drop policy if exists "Workflows access own" on workflows;
create policy "Workflows access own" on workflows for all using (auth.uid() = user_id);

-- HOUSEHOLDS
drop policy if exists "Households read member" on households;
drop policy if exists "Households read authenticated" on households;
create policy "Households read authenticated" on households for select using (
  auth.role() = 'authenticated'
);

drop policy if exists "Households insert authenticated" on households;
create policy "Households insert authenticated" on households for insert with check (
  auth.role() = 'authenticated'
);

-- CONDITIONS (Read-Only Public Lookup)
drop policy if exists "Conditions are viewable by everyone" on conditions;
create policy "Conditions are viewable by everyone" on conditions for select using (true);

-- USER CONDITIONS (User Scoped)
drop policy if exists "Users manage own conditions" on user_conditions;
create policy "Users manage own conditions" on user_conditions for all using (auth.uid() = user_id);

-- FRIENDSHIPS (Shared Read, User Insert/Delete)
drop policy if exists "Users view own friendships" on friendships;
create policy "Users view own friendships" on friendships for select using (auth.uid() = user_id or auth.uid() = friend_id);

drop policy if exists "Users manage own friendships" on friendships;
create policy "Users manage own friendships" on friendships for all using (auth.uid() = user_id);

-- ========================================================
-- TRIGGERS
-- ========================================================

-- Automatically create public.users row on signup
create or replace function public.handle_new_user()
returns trigger 
language plpgsql 
security definer
set search_path = public
as $$
declare
  new_household_id uuid;
begin
  -- Create a new household for the user
  insert into public.households (name) 
  values (split_part(new.email, '@', 1) || '''s Household')
  returning id into new_household_id;

  -- Create user linked to household
  insert into public.users (id, display_name, avatar_url, metabolic_state_json, streak_count, calorie_target, household_id)
  values (
    new.id,
    split_part(new.email, '@', 1),
    null,
    '{"current_goal":"maintenance"}',
    0,
    2000,
    new_household_id
  );
  return new;
end;
$$;

-- Re-create trigger
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Streak calculation trigger
create or replace function public.calculate_streak_on_log()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_last_log_date date;
  v_today date := (to_char(now() at time zone 'UTC', 'YYYY-MM-DD'))::date;
  v_days_diff integer;
begin
  select max(local_date::date) into v_last_log_date 
  from public.logs 
  where user_id = new.user_id and local_date::date < v_today;

  if v_last_log_date is null then
    update public.users set streak_count = greatest(1, coalesce(streak_count, 0)) where id = new.user_id;
  else
    v_days_diff := v_today - v_last_log_date;
    if v_days_diff = 1 then
      if (select count(*) from public.logs where user_id = new.user_id and local_date::date = v_today) = 1 then
        update public.users set streak_count = coalesce(streak_count, 0) + 1 where id = new.user_id;
      end if;
    elsif v_days_diff > 1 then
      update public.users set streak_count = 1 where id = new.user_id;
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists on_log_inserted on public.logs;
create trigger on_log_inserted
  after insert on public.logs
  for each row execute procedure public.calculate_streak_on_log();

-- ========================================================
-- 13. SUBSCRIPTIONS (Stripe)
-- ========================================================
create table if not exists subscriptions (
  id text primary key, -- Stripe Subscription ID
  user_id uuid references users(id) not null,
  status text not null, -- active, past_due, canceled
  price_id text not null,
  current_period_end timestamptz not null,
  created_at timestamptz default now()
);
create index if not exists idx_subscriptions_user_id on subscriptions(user_id);

alter table subscriptions enable row level security;

drop policy if exists "Users view own subscription" on subscriptions;
create policy "Users view own subscription" on subscriptions for select using (auth.uid() = user_id);

-- ========================================================
-- 14. VOUCHERS (Custom Access Codes)
-- ========================================================
create table if not exists vouchers (
  id uuid default gen_random_uuid() primary key,
  code text unique not null,
  type text not null, -- e.g., 'oteka_plus_30d', 'discount_50'
  is_redeemed boolean default false,
  redeemed_by uuid references users(id),
  redeemed_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz default now()
);
create index if not exists idx_vouchers_redeemed_by on vouchers(redeemed_by);

alter table vouchers enable row level security;

drop policy if exists "Users view their own redeemed vouchers" on vouchers;
create policy "Users view their own redeemed vouchers" on vouchers for select using (auth.uid() = redeemed_by);

-- ========================================================
-- 15. STORAGE CONFIGURATION
-- ========================================================

-- Ensure the bucket exists
insert into storage.buckets (id, name, public) 
values ('food_scans', 'food_scans', false) 
on conflict (id) do nothing;

-- Allow users to upload their own scans
drop policy if exists "Users can upload own scans" on storage.objects;
create policy "Users can upload own scans" on storage.objects for insert with check (
  bucket_id = 'food_scans' and 
  auth.role() = 'authenticated' and
  (storage.foldername(name))[1] = auth.uid()::text
);

-- Allow users to view their own scans
drop policy if exists "Users can view own scans" on storage.objects;
create policy "Users can view own scans" on storage.objects for select using (
  bucket_id = 'food_scans' and 
  auth.role() = 'authenticated' and
  (storage.foldername(name))[1] = auth.uid()::text
);

-- ========================================================
-- 16. REALTIME CONFIGURATION
-- ========================================================

-- Enable realtime for logs table
alter publication supabase_realtime add table logs;

-- ========================================================
-- 17. AUTOMATED CRON SCHEDULING (pg_cron)
-- ========================================================

-- Enable the pg_cron extension safely
create extension if not exists pg_cron;

-- Loop function to run decay cycle for all active users
create or replace function public.run_all_entropy_cycles()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  user_record record;
begin
  for user_record in select id from public.users loop
    perform public.run_entropy_cycle(user_record.id);
  end loop;
end;
$$;

-- Unschedule the job if it already exists to ensure idempotency on rerun
select cron.unschedule('daily-entropy-decay-job')
from cron.job
where jobname = 'daily-entropy-decay-job';

-- Schedule the decay cycle daily at midnight UTC
select cron.schedule(
  'daily-entropy-decay-job',
  '0 0 * * *',
  $$ select public.run_all_entropy_cycles(); $$
);
