-- Enable Extensions
create extension if not exists vector;

-- 1. HOUSEHOLDS (Shared Pantry Context)
create table if not exists households (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  created_at timestamptz default now()
);

-- 2. USERS
create table if not exists users (
  id uuid references auth.users not null primary key,
  display_name text,
  metabolic_state_json jsonb default '{"current_goal": "maintenance"}'::jsonb,
  hand_width_mm numeric,
  streak_count integer default 0,
  household_id uuid references households(id),
  created_at timestamptz default now()
);

-- 3. FOODS
create table if not exists foods (
  id bigint generated by default as identity primary key,
  name text not null,
  density_coefficient numeric default 1.0, -- g/cm3
  category_decay_rate numeric default 0.05, -- k
  barcode_upc text,
  -- structure example (app level):
  -- {
  --   "kcal_per_100g": 120,
  --   "protein_g": 7,
  --   "carbs_g": 12,
  --   "fat_g": 4,
  --   "tags": ["gluten-free", "high-protein", "low-FODMAP"],
  --   "condition_safe_for": ["coeliac", "t2d"],
  --   "condition_risk_for": ["pancreatitis"]
  -- }
  nutritional_info jsonb
);

-- 4. PANTRY
create table if not exists pantry (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) not null,
  household_id uuid references households(id),
  food_id bigint references foods(id),
  probability_score numeric default 1.0,
  last_verified_at timestamptz default now(),
  status text default 'active' -- 'active' | 'review_needed' | 'consumed'
);

-- 5. FRIENDSHIPS
create table if not exists friendships (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) not null,
  friend_id uuid references users(id) not null,
  status text default 'pending', -- 'pending' | 'accepted'
  created_at timestamptz default now(),
  unique(user_id, friend_id)
);

-- 6. CONDITIONS (Global definitions)
-- Use text IDs like 'coeliac', 't2d', etc. for easier seeding.
create table if not exists conditions (
  id text primary key,
  name text not null,
  category text,
  strictness text,
  diet_impact text,
  rules_json jsonb not null,
  dga_score numeric default 1.0,
  never_recommend_json jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

-- 7. USER_CONDITIONS (Join)
create table if not exists user_conditions (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) not null,
  condition_id text references conditions(id) not null,
  created_at timestamptz default now(),
  unique(user_id, condition_id)
);

-- 8. METABOLIC PHENOMENA (Prompt templates)
-- Use text IDs like 'randle_cycle'.
create table if not exists metabolic_phenomena (
  id text primary key,
  name text not null,
  category text,
  mechanism text,
  deepseek_prompt_template text not null,
  created_at timestamptz default now()
);

-- 9. WORKFLOWS (Audit + state)
create table if not exists workflows (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references users(id) not null,
  trigger_event text not null,
  last_run_status text default 'pending',
  logs_json jsonb,
  created_at timestamptz default now()
);

-- 10. LOGS
create table if not exists logs (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) not null,
  workflow_id uuid references workflows(id),
  grams numeric,
  metabolic_tags_json jsonb,
  captured_at timestamptz default now()
);

-- 11. CACHE ENTRIES (Advisor/LLM caching)
create table if not exists cache_entries (
  key text primary key,
  value jsonb not null,
  expires_at timestamptz not null
);
create index if not exists idx_cache_expires on cache_entries(expires_at);

-- RLS SECURITY POLICIES
alter table users enable row level security;
alter table foods enable row level security;
alter table pantry enable row level security;
alter table friendships enable row level security;
alter table households enable row level security;
alter table logs enable row level security;
alter table workflows enable row level security;
alter table conditions enable row level security;
alter table user_conditions enable row level security;
alter table metabolic_phenomena enable row level security;
alter table cache_entries enable row level security;

-- USERS
create policy if not exists "Users view own profile"
  on users for select using (auth.uid() = id);

create policy if not exists "Users update own profile"
  on users for update using (auth.uid() = id);

create policy if not exists "Authenticated view profiles"
  on users for select using (auth.role() = 'authenticated');

-- FOODS
create policy if not exists "Foods read (auth)"
  on foods for select using (auth.role() = 'authenticated');

create policy if not exists "Foods insert (auth)"
  on foods for insert with check (auth.role() = 'authenticated');

-- PANTRY
create policy if not exists "Pantry read own"
  on pantry for select using (auth.uid() = user_id);

create policy if not exists "Pantry write own"
  on pantry for insert with check (auth.uid() = user_id);

create policy if not exists "Pantry update own"
  on pantry for update using (auth.uid() = user_id);

-- FRIENDSHIPS
create policy if not exists "Friendships read own"
  on friendships for select using (auth.uid() = user_id or auth.uid() = friend_id);

create policy if not exists "Friendships insert requester"
  on friendships for insert with check (auth.uid() = user_id);

create policy if not exists "Friendships update receiver"
  on friendships for update using (auth.uid() = friend_id);

-- HOUSEHOLDS
create policy if not exists "Households read member"
  on households for select using (
    exists (select 1 from users u where u.id = auth.uid() and u.household_id = households.id)
  );

-- CONDITIONS
create policy if not exists "Conditions read (auth)"
  on conditions for select using (auth.role() = 'authenticated');

-- USER_CONDITIONS
create policy if not exists "User conditions read own"
  on user_conditions for select using (auth.uid() = user_id);

create policy if not exists "User conditions write own"
  on user_conditions for insert with check (auth.uid() = user_id);

create policy if not exists "User conditions delete own"
  on user_conditions for delete using (auth.uid() = user_id);

-- METABOLIC PHENOMENA
create policy if not exists "Metabolic phenomena read (auth)"
  on metabolic_phenomena for select using (auth.role() = 'authenticated');

-- LOGS / WORKFLOWS
create policy if not exists "Logs read own"
  on logs for select using (auth.uid() = user_id);

create policy if not exists "Logs insert own"
  on logs for insert with check (auth.uid() = user_id);

create policy if not exists "Workflows read own"
  on workflows for select using (auth.uid() = user_id);

create policy if not exists "Workflows insert own"
  on workflows for insert with check (auth.uid() = user_id);

-- CACHE ENTRIES
create policy if not exists "Cache read (auth)"
  on cache_entries for select using (auth.role() = 'authenticated');

create policy if not exists "Cache write (auth)"
  on cache_entries for insert with check (auth.role() = 'authenticated');

-- Trigger: create public.users row on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, display_name, metabolic_state_json, streak_count)
  values (
    new.id,
    split_part(new.email, '@', 1),
    '{"current_goal":"maintenance"}',
    0
  );
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
