'use client';

import { motion } from 'framer-motion';
import { ChevronLeft, Scale, ShieldCheck, AlertTriangle } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { BottomNav } from '@/components/layout/BottomNav';

export default function TermsPage() {
  const router = useRouter();

  return (
    <div className="min-h-screen bg-[var(--bg-app)] text-[var(--text-primary)] p-6 pb-32 transition-colors duration-500 font-sans">
      
      {/* Header */}
      <header className="flex items-center gap-4 pt-safe mb-8">
        <button 
            onClick={() => router.back()}
            className="p-2 -ml-2 rounded-full hover:bg-black/5 dark:hover:bg-white/10 text-[var(--text-secondary)] transition-colors"
        >
            <ChevronLeft size={24} />
        </button>
        <div>
           <h1 className="text-3xl font-black tracking-tight mb-1">Terms</h1>
           <p className="text-[var(--text-secondary)] text-sm font-bold uppercase tracking-widest">Usage Protocols</p>
        </div>
      </header>

      <div className="space-y-6 max-w-2xl mx-auto">
        <div className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-[32px] p-6 shadow-sm overflow-hidden relative">
            <div className="absolute top-0 right-0 p-4 opacity-5">
                <Scale size={100} strokeWidth={1} />
            </div>
            <p className="text-[10px] text-[var(--text-secondary)] font-black uppercase tracking-widest mb-4">Last Revision: 2026.04</p>
            <p className="text-sm text-[var(--text-primary)] leading-relaxed font-medium">
                By initializing the Oteka Neural Engine, you acknowledge and agree to the following biological and digital protocols.
            </p>
        </div>

        <div className="space-y-4">
            {[
                {
                    icon: ShieldCheck,
                    title: "Data Sovereignty",
                    content: "Your metabolic logs, biometric data, and pantry inventory are stored securely. You maintain full ownership and may request permanent deletion of your identity cluster at any time."
                },
                {
                    icon: AlertTriangle,
                    title: "Medical Disclaimer",
                    content: "Oteka is a nutritional intelligence tool. Recommendations generated by Gemini and DeepSeek are for optimization purposes and do not constitute professional medical diagnosis or treatment."
                },
                {
                    icon: Scale,
                    title: "Volumetric Accuracy",
                    content: "Visual caloric estimation is an approximation based on volumetric density. Users with critical health conditions should verify AI outputs against clinical standards."
                }
            ].map((item, idx) => (
                <motion.div 
                    key={idx}
                    initial={{ opacity: 0, x: -10 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: idx * 0.1 }}
                    className="p-6 bg-[var(--bg-surface)] border border-[var(--border)] rounded-[28px] shadow-sm flex gap-4"
                >
                    <div className="shrink-0 pt-1">
                        <item.icon size={18} className="text-[var(--primary)]" />
                    </div>
                    <div>
                        <h3 className="font-black text-xs uppercase tracking-widest mb-2">{item.title}</h3>
                        <p className="text-xs text-[var(--text-secondary)] leading-relaxed font-medium">{item.content}</p>
                    </div>
                </motion.div>
            ))}
        </div>

        <div className="bg-[var(--primary)]/5 border border-[var(--primary)]/10 p-6 rounded-[28px] text-center">
            <p className="text-[10px] text-[var(--primary)] font-black uppercase tracking-[0.2em]">Oteka AI Core v3.0</p>
        </div>
      </div>

      <BottomNav />
    </div>
  );
}
